### ISSUE TITLE
Can’t download "simple-knn" submodule

### ISSUE THREAD

**Issue by AndingDrLin** [apple/ml-hugs#11]
The link to simple-knn in this repo is not working, so that I can't download the submodule.

**Comment by AndingDrLin** [comment]
And there is another problem that when I performed evaluation, I met this:
```
Traceback (most recent call last):
  File "scripts/evaluate.py", line 19, in <module>
    from hugs.trainer import GaussianTrainer
  File "/home/ubuntu/lyj/Project/HUGS/./hugs/trainer/__init__.py", line 6, in <module>
    from .gs_trainer import GaussianTrainer
  File "/home/ubuntu/lyj/Project/HUGS/./hugs/trainer/gs_trainer.py", line 27, in <module>
    from hugs.models.hugs_trimlp import HUGS_TRIMLP
  File "/home/ubuntu/lyj/Project/HUGS/./hugs/models/__init__.py", line 1, in <module>
    from .scene import SceneGS
  File "/home/ubuntu/lyj/Project/HUGS/./hugs/models/scene.py", line 20, in <module>
    from simple_knn._C import distCUDA2
ModuleNotFoundError: No module named 'simple_knn'
```
I have installed this submodule and installed simple_knn in my conda environment using pip

**Comment by LarkLeeOnePiece** [comment]
> And there is another problem that when I performed evaluation, I met this:
> 
> ```
> Traceback (most recent call last):
>   File "scripts/evaluate.py", line 19, in <module>
>     from hugs.trainer import GaussianTrainer
>   File "/home/ubuntu/lyj/Project/HUGS/./hugs/trainer/__init__.py", line 6, in <module>
>     from .gs_trainer import GaussianTrainer
>   File "/home/ubuntu/lyj/Project/HUGS/./hugs/trainer/gs_trainer.py", line 27, in <module>
>     from hugs.models.hugs_trimlp import HUGS_TRIMLP
>   File "/home/ubuntu/lyj/Project/HUGS/./hugs/models/__init__.py", line 1, in <module>
>     from .scene import SceneGS
>   File "/home/ubuntu/lyj/Project/HUGS/./hugs/models/scene.py", line 20, in <module>
>     from simple_knn._C import distCUDA2
> ModuleNotFoundError: No module named 'simple_knn'
> ```
> 
> I have installed this submodule and installed simple_knn in my conda environment using pip

Could you see the package name"simple_knn" when you used "conda list"?

**Comment by AndingDrLin** [comment]
Dear Lark Lee,
Yes, I can see it in my conda environment but it still says this module is not installed...[image]

Yujia Lin
Glasgow College, University of Electronic Science and Technology of China
Chengdu, Sichuan

> From: "Lark ***@***.***>
> Date:  Fri, Jul 12, 2024, 13:04
> Subject:  Re: [apple/ml-hugs] Can’t download "simple-knn" submodule (Issue #11)
> To: ***@***.***>
> Cc: "Yujia ***@***.***>, "State ***@***.***>
> > And there is another problem that when I performed evaluation, I met this:Traceback (most recent call last):
  File "scripts/evaluate.py", line 19, in <module>
    from hugs.trainer import GaussianTrainer
  File "/home/ubuntu/lyj/Project/HUGS/./hugs/trainer/__init__.py", line 6, in <module>
    from .gs_trainer import GaussianTrainer
  File "/home/ubuntu/lyj/Project/HUGS/./hugs/trainer/gs_trainer.py", line 27, in <module>
    from hugs.models.hugs_trimlp import HUGS_TRIMLP
  File "/home/ubuntu/lyj/Project/HUGS/./hugs/models/__init__.py", line 1, in <module>
    from .scene import SceneGS
  File "/home/ubuntu/lyj/Project/HUGS/./hugs/models/scene.py", line 20, in <module>
    from simple_knn._C import distCUDA2
ModuleNotFoundError: No module named 'simple_knn'
I have installed this submodule and installed simple_knn in my conda environment using pip

**Comment by Daydreamer-f** [comment]
try this: pip install git+https://gitlab.inria.fr/bkerbl/simple-knn.git

**Comment by AndingDrLin** [comment]
> try this: pip install git+https://gitlab.inria.fr/bkerbl/simple-knn.git

@Daydreamer-f Well, thank you. But it still not work...

**Comment by gilbert248** [comment]
> > try this: pip install git+https://gitlab.inria.fr/bkerbl/simple-knn.git
> 
> @Daydreamer-f Well, thank you. But it still not work...

or you could try typing "git clone https://gitlab.inria.fr/bkerbl/simple-knn.git" in this directory: ml-hugs/submodules/
then "cd simple-knn" and "pip install ."

**Comment by AndingDrLin** [comment]
> > > try this: pip install git+https://gitlab.inria.fr/bkerbl/simple-knn.git
> > 
> > 
> > @Daydreamer-f Well, thank you. But it still not work...
> 
> or you could try typing "git clone https://gitlab.inria.fr/bkerbl/simple-knn.git" in this directory: ml-hugs/submodules/ then "cd simple-knn" and "pip install ."

I tried this and it still raised the error that there is no `simple-knn` in my environment. What is your OS and CUDA version? Maybe I can retry it using your settings. 
Btw, it should be `pip install ./` in your advice rather than `pip install`.

**Comment by Daydreamer-f** [comment]
> > > > try this: pip install git+https://gitlab.inria.fr/bkerbl/simple-knn.git
> > > 
> > > 
> > > @Daydreamer-f Well, thank you. But it still not work...
> > 
> > 
> > or you could try typing "git clone https://gitlab.inria.fr/bkerbl/simple-knn.git" in this directory: ml-hugs/submodules/ then "cd simple-knn" and "pip install ."
> 
> I tried this and it still raised the error that there is no `simple-knn` in my environment. What is your OS and CUDA version? Maybe I can retry it using your settings. Btw, it should be `pip install ./` in your advice rather than `pip install`.

I simply type this command in the conda environment which is the same as the one hugs required. I changed `torch` version to 1.21.0 and `CUDA` version remain 11.7 to fix the pytorch3d version. 
Did you meet any errors when installing `simple-knn` using pip? And when you installed it successfully, can you try these command in your conda environment:
> python
> import simple-knn

And report what happened?
(我之前安装simple-knn的时候也遇到过一些报错，比如torch和CUDA版本不符，但都是在安装的时候报的error，simple-knn一般成功安装了运行的时候都没有问题。所以你确定你成功安装了吗？）

**Comment by yu-jingrui** [comment]
I have a similar problem. Submodules are not installed while running conda_setup.sh. The error message is 

> RuntimeError:
> The detected CUDA version (12.5) mismatches the version that was used to compile
> PyTorch (11.7). Please make sure to use the same CUDA versions.

CUDA 12.5 is my system cuda version. I installed cuda 11.7 in the hugs env, but pip does not recognize it and still show the same error.

**Comment by yu-jingrui** [comment]
> I have a similar problem. Submodules are not installed while running conda_setup.sh. The error message is
> 
> > RuntimeError:
> > The detected CUDA version (12.5) mismatches the version that was used to compile
> > PyTorch (11.7). Please make sure to use the same CUDA versions.
> 
> CUDA 12.5 is my system cuda version. I installed cuda 11.7 in the hugs env, but pip does not recognize it and still show the same error.

I solved this after consulting claude.ai. `CUDA_HOME` needs to be specified manually as `/home/myusername/miniconda3/envs/hugs`. After this, pip reports g++ version is too new (14.x on archlinux) for pytorch-cuda 11.7, which needs to be >6.0 <11.5. Then I `conda install gxx_linux-64`, which installed gxx_linux-64 version 11.2. This solved the problem. Then I could install the submodules using the commands `pip install submodules/simple-knn` and `pip install submodules/diff-gaussian-rasterization`.
